config/routes.rb
Rails.application.routes.draw do
  # get 'courses/index'
  # get 'courses/show'
  
  # map.devise_for :users
  # map.resources :users, :has_one: address

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_for :users
  resources :courses, :enrollments
  resources :users, only: [:show, :edit, :update]
  root to: "courses#index"

  get 'postedcourses' => "courses#posted"
  get 'search' => "courses#search"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
before_action :authenticate_user!, except: %i[index show]
before_action :find_course, only: %i[show edit update destroy]

def index
  @courses = Course.includes(:user).all  #find this to optimise load times

end

def new
  @course = Course.new
  @categories = Category.all
  @address = Address.new
  @address.build_courses
end

def create
  #checks if user is instructor. if so, allow them to create courses.
  if current_user.instructor

  @course = current_user.courses.new(course_params)
  @course.user_id = current_user.id
  
  if @course.save
    redirect_to @course
  else
    flash.now[:messages] = @course.errors.full_messages[0]
    render :new
  end
else
  flash.now[:messages] = "You must be an instructor to post courses."
  redirect_to root_path
  end
end

def show
  @course = Course.find(params[:id])
  @category = Category.find(@course.category_id)
end


def posted

  @courses = Course.where(user_id: current_user.id)

end





def edit
  @course = Course.find(params[:id])
end

def update
  if @course.update(course_params)

  redirect_to @course
  else
      flash.now[:messages] = @course.errors.full_messages[0]
      render :edit
  end


end



def destroy
  @course.destroy

  redirect_to posted_courses


end




private

def find_course
  @course = Course.find(params[:id])
end
def course_params
   params.require(:course).permit(:title, :start_time, :end_time, :url, :instructor_role, :duration, :description, :fee, :online, :instructor_name, :practice_management, :substantive_law, :ethics, :professional_skills, :category_id, :picture, :user_id, address_attributes: [:address_line_1, :address_line_2, :suburb, :state, :postcode])
end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="mb-3">
<%= form_with model: @course do |form|  %>     
    
    <div><%= form.label :title %>
    <%= form.text_field :title %></div>


    <div><%= form.label :description %>
    <%= form.text_area :description %></div>
        <div><%= form.label :online %>
    <%= form.check_box :online %></div>




    <div><%= form.label :start_time %>
    <%= form.datetime_field :start_time %> </div>
        <div><%= form.label :end_time %>
    <%= form.datetime_field :end_time %> </div>
        <div><%= form.label :duration %>
    <%= form.time_field :duration %> </div>

    <div><%= form.label :fee %>
    <%= form.text_field :fee %></div>

    <div><%= form.label :instructor_name %>
    <%= form.text_field :instructor_name %></div>
        <div><%= form.label :instructor_role %>
    <%= form.text_field :instructor_role %></div>
    
    <div><%= form.label :practice_management %>
    <%= form.number_field :practice_management, min: 0, max: 10 %></div>
        <div><%= form.label :ethics %>
        <%= form.number_field :ethics, min: 0, max: 10 %></div>
        <div><%= form.label :professional_skills %>
    <%= form.number_field :professional_skills, min: 0, max: 10 %></div>
        <div><%= form.label :substantive_law %>
    <%= form.number_field :substantive_law, min: 0, max: 10 %></div>    
        
        
        

        <div>    <%= form.label :category %>
    <%= form.collection_select :category_id, Category.all, :id, :category %></div>





        <div><%= form.label :url %>
    <%= form.text_field :url %></div>
    
    
    

        <div><%= form.label :picture %>
    
    <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg' %></div>
            <%# address field - currently inoperable %>
            <%= form.fields_for :address do |address_form| %>
        <div><%= address_form.label :address_line_1 %>
            <%= address_form.text_field :address_line_1 %></div>
            <div><%= address_form.label :address_line_2 %>
            <%= address_form.text_field :address_line_2 %></div>
                <div><%= address_form.label :suburb %>
            <%= address_form.text_field :suburb %></div>
                    <div><%= address_form.label :state %>
            <%= address_form.text_field :state %></div>
                        <div><%= address_form.label :state %>
                        <%= address_form.text_field :state %></div>
            <div><%= address_form.label :postcode %>
            <%= address_form.number_field :postcode, min: 800, max: 9999 %></div>
        <% end %>




    <%= form.submit %>
  </div>


<% end %>

app/views/courses/_message.html.erb
<li><%= message %></li>

app/views/courses/edit.html.erb
<h3>Edit Course <%= @course.title %></h3>

<%= render 'form' %>

app/views/courses/index.html.erb
<%# <div class="container"> %>



<div class="row">

<% @courses.each_slice(1) do |courses| %>
  <div class="col-lg-5 mainboxes">
    <% courses.each do |course| %>
      <h3><%= course.title %></h3>
         <p><% if course.fee.present? %>
              $<%= course.fee %>
              <% else %>
              Free Course
              <% end  %></p>
                <p>
          
          
           <%= link_to 'View', course_path(course) %>

     <% end %>
     
     </div>
     
     
     <% end %>
     
<%# </div> %>
</div>

app/views/courses/new.html.erb
<h3>Add a new Course </h3>



<%= render 'form' %>

app/views/courses/posted.html.erb
<h3> My Course Listings </h3>

<% @courses.each do |course| %>
  <h3><%= course.title %></h3>
  <p><%= course.description %></p>
      <p><%= link_to 'View', course_path(course) %></p>
      <p><%= link_to 'Edit', edit_course_path(course) %></p>
      <p><%= link_to 'Delete', course_path(course), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
  
  

app/views/courses/show.html.erb
<h3><%= @course.title %></h3>

  <div class="container">
   <div class="row">

   <div class="col-sm-8">
  <p><%= @course.description %></p></div>
<div class="col-sm-4">
      <p><%= image_tag @course.picture if @course.picture.attached? %></p>
      <p><%= @course.instructor_name %></p>
      <p><%= @course.instructor_role %></p>
          <p>Category: <%= @category.category %></p>
          <p><% if @course.fee.present? %>
              $<%= @course.fee %>
              <% else %>
              Free Course
              <% end  %></p>
    
                <% if @course.online.present? %>
                Online Course
                <% else %>
                <p><%= @course.start_time %></p>
                <p><%= @course.end_time %></p>
                <% end  %>
      
          <%# CPD points below only displays if the values are more than 0 %>
          <% if @course.practice_management.present? %><p>Practice Management Skills: <%= @course.practice_management %> points</p><% end %>
          
          <% if @course.substantive_law.present? %><p>Substantive Law: <%= @course.substantive_law %> points</p><% end %>
          
          <% if @course.ethics.present? %><p>Ethics: <%= @course.ethics %> points</p><% end %>
    
          <% if @course.professional_skills.present? %><p>Professional Skills: <%= @course.professional_skills %> points</p></p><% end %>
  </div></div>
  <div class="row">        

<div class="sm-12"> <% if @course.url.present? %><a href="<%= @course.url %>" target="_blank">Link to Course</a> <% end %></div></div>
<div class="row"><div class="sm-12">
                        <div class="row">        

<div class="sm-12">
                      <%= button_to 'Add to my Courses', enrollments_path(@course),  method: :post, params: {course_id:@course.id} %>
</div></div>
          <% if user_signed_in? && current_user.id == @course.user.id %>
            <%= link_to 'Edit this Course', edit_course_path(@course) %>
            <%= link_to 'Delete this Course', course_path(@course), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %> 
          <% end %>
            <% if user_signed_in? %>

            <% end %></div></div></div>